# 2. Наивный байесовский классификатор

Загрузите датасеты digits и breast_cancer из sklearn.datasets. Выведите несколько строчек из обучающих выборок и посмотрите на признаки. С помощью sklearn.model_selection.cross_val_score c настройками по умолчанию и вызова метода mean() у возвращаемого этой функцией numpy.ndarray, сравните качество работы наивных байесовских классификаторов на этих двух датасетах. Для сравнения предлагается использовать BernoulliNB, MultinomialNB и GaussianNB. Насколько полученные результаты согласуются с вашими ожиданиями?
    
Два датасета, конечно, еще не повод делать далеко идущие выводы, но при желании вы можете продолжить исследование на других выборках (например, из UCI репозитория).

Ответьте (прямо в ipynb блокноте с вашими экспериментами) на вопросы:
1. Каким получилось максимальное качество классификации на датасете breast_cancer? 

    > 0.9367
2. Каким получилось максимальное качество классификации на датасете digits?

    > 0.8709
3. Какие утверждения из приведенных ниже верны?
    
    (a) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли
    
    (b) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением
    
    (c) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков
    
    (d) На вещественных признаках лучше всего сработало нормальное распределение
    > (c), (d)

In [1]:
from sklearn import datasets, metrics, naive_bayes
from sklearn.model_selection import cross_val_score
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()
sets = [[digits, "digits"], [breast_cancer, "breast_cancer"]]
print digits.data[:5].T
print breast_cancer.data[:5]

[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  5.   0.   0.   7.   0.]
 [ 13.  12.   4.  15.   1.]
 [  9.  13.  15.  13.  11.]
 [  1.   5.  12.   1.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   8.   0.]
 [ 13.   0.   3.  13.   0.]
 [ 15.  11.  16.   6.   7.]
 [ 10.  16.  15.  15.   8.]
 [ 15.   9.  14.   4.   0.]
 [  5.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  3.   0.   0.   2.   0.]
 [ 15.   3.   8.   1.   1.]
 [  2.  15.  13.  13.  13.]
 [  0.  16.   8.  13.   6.]
 [ 11.   6.  16.   0.   2.]
 [  8.   0.   0.   0.   2.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  4.   7.   0.   0.   0.]
 [ 12.  15.   1.   2.   7.]
 [  0.  16.   6.  15.  15.]
 [  0.  16.  15.  11.   0.]
 [  8.   2.  11.   1.   9.]
 [  8.   0.   0.   0.   8.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  5.   0.   1.   0.   5.]
 [  8.   1.   8.   0.  16.]
 [  0.  16.  13.   1

In [3]:
classifiers = [
                [naive_bayes.BernoulliNB(), "BernoulliNB"],
                [naive_bayes.MultinomialNB(), "MultinomialNB"],
                [naive_bayes.GaussianNB(), "GaussianNB"],
              ]

In [4]:
for s in sets:
    for est in classifiers:
        print "%s %s %s"%(est[1], s[1], 
                cross_val_score(est[0], s[0].data, s[0].target).mean(0))

BernoulliNB digits 0.825823650778
MultinomialNB digits 0.870877148974
GaussianNB digits 0.818600380355
BernoulliNB breast_cancer 0.627420402859
MultinomialNB breast_cancer 0.894579040193
GaussianNB breast_cancer 0.936749280609
